'\" t
.\" Man page skeleton by Dale Scheetz <dwarf@polaris.net>.
.\" Man page improved by Chris Fearnley <cjf@netaxs.com>.
.TH ucblogo 1 "13 Sep 96" "Debian Linux"
.SH NAME
ucblogo \- a dialect of lisp using turtle graphics famous for teaching kids.

.SH SYNOPSIS
\fBucblogo\fP  [script ...]

.SH DESCRIPTION

.LP
This version of Logo is designed for a machine with adequate memory.  It is
not likely to be usable as the basis for a 64K microcomputer
implementation.

This is the UC Berkeley implementation of logo written primarily by
Daniel Van Blerkom, Brian Harvey, Michael Katz, and Douglas Orleans.  This
version of logo is featured in Brian Harvey's book _Computer Science Logo
Style: Volume 1: Symbolic Computing_ (ISBN 0-262-58151-5).

.SH AUTHOR
Primarily written by Daniel Van Blerkom, Brian Harvey,
Michael Katz, and Douglas Orleans.  Thanks to Fred Gilham for the X11 code.
Send comments by e-mail to bh@cs.berkeley.edu. 

.SH SEE ALSO

Brian Harvey's book _Computer_Science_Logo_Style, _Volume_1:
_Symbolic_Computing_ (ISBN 0-262-58151-5).

/usr/doc/ucblogo/usermanual
