.TH LOGO 1
.SH NAME
logo, logo-wx \- start the Logo Programming Language interpreter
.SH SYNOPSIS
.B logo
[\fIfile\fR]
.SH DESCRIPTION
.B logo
begins running the logo programming language interperter. If a file is
provided, it will run those commands first.  The full manual is available
as
.PP
.B info ucblogo
